apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: devopsbabu16/wisecow:latest
        ports:
        - containerPort: 4499
          hostPort: 4499  # bind container port to EC2 host port
