apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: ClusterIP  # internal service only
  ports:
    - protocol: TCP
      port: 4499
      targetPort: 4499
